# .github/workflows/run_tests.yml
name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        issue:
          [
            issue_1,
            issue_2,
            issue_3,
            issue_4,
            issue_5,
            issue_6,
            issue_7,
            practice_1,
            practice_2,
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r ${{ matrix.issue }}/requirements.txt
      - run: pytest
        working-directory: ${{ matrix.issue }}
